# Generated by Django 4.0.4 on 2022-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffwc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='random',
            field=models.CharField(default=223, max_length=200),
            preserve_default=False,
        ),
    ]
