# Generated by Django 4.0.4 on 2022-05-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffwc_app', '0002_user_data_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='random',
        ),
    ]
