# Generated by Django 4.0.4 on 2022-05-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffwc_app', '0003_remove_user_data_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='weight_update',
            field=models.FloatField(default=231),
            preserve_default=False,
        ),
    ]
