# Generated by Django 4.0.4 on 2022-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffwc_app', '0007_alter_user_data_weight_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='goal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
