# Generated by Django 4.0.4 on 2022-05-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffwc_app', '0009_alter_user_data_goal_weight_alter_user_data_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='weight_update',
        ),
        migrations.CreateModel(
            name='Weight_Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_update', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ffwc_app.user_data')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
