# Generated by Django 4.0.4 on 2022-05-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffwc_app', '0010_remove_user_data_weight_update_weight_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.CharField(max_length=5000)),
                ('group_weight', models.FloatField()),
                ('group_goal_weight', models.FloatField()),
            ],
        ),
    ]
