# Generated by Django 4.0.4 on 2022-05-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffwc_app', '0011_group_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group_Data',
        ),
    ]
